name: Test pull request

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  test-dev:
    runs-on: [dev]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fin des tests
        run: echo OK


  deploy-prod:
    needs: [test-dev]
    # if: ${{ github.event_name =='push' && github.ref_name == 'main' }}
    runs-on: [prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start prod
        run: echo PROD